- hosts: all
  become: true
  tasks:

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Pull calculator docker image
      community.docker.docker_image:
        name: anubhavmohanty/calculator
        source: pull

    - name: Launch the calculator container
      docker_container:
        name: calculator
        image: anubhavmohanty/calculator
        state: started
        
