- hosts: all
  become: true
  tasks:
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
  
    - name: Pull calculator docker image
      community.docker.docker_image:
        name: anubhavmohanty/calculator
        source: pull

    - name: Launch the calculator container
      docker_container:
        name: calculator
        image: anubhavmohanty/calculator
        state: started
        
